@extends('enfas.layout')
@section('title','Disponibilidade')
@section('page_title','Disponibilidade, férias e bloqueios')
@section('page_subtitle','Grade semanal por profissional e unidade.')
@section('content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="row g-4 mb-4"><div class="col-xl-6"><div class="card ea-v8-card"><div class="card-header border-0"><strong>Novo horário</strong></div><form method="POST" action="{{ route('v8.availability.store') }}">@csrf<div class="card-body row g-3">
<div class="col-md-6"><label class="form-label">Profissional</label><select class="form-select" name="professional_id">@foreach($professionals as $p)<option value="{{ $p->id }}">{{ $p->name }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Unidade</label><select class="form-select" name="location_id"><option value="">Todas</option>@foreach($locations as $l)<option value="{{ $l->id }}">{{ $l->name }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">Dia</label><select class="form-select" name="weekday">@foreach(['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'] as $i=>$d)<option value="{{ $i }}">{{ $d }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Início</label><input class="form-control" type="time" name="starts_at" required></div><div class="col-md-3"><label class="form-label">Fim</label><input class="form-control" type="time" name="ends_at" required></div><div class="col-md-2"><label class="form-label">Slot</label><input class="form-control" type="number" name="slot_minutes" value="30"></div>
</div><div class="card-footer bg-transparent"><button class="btn btn-primary">Adicionar</button></div></form></div></div>
<div class="col-xl-6"><div class="card ea-v8-card"><div class="card-header border-0"><strong>Ausência / férias</strong></div><form method="POST" action="{{ route('v8.absences.store') }}">@csrf<div class="card-body row g-3"><div class="col-12"><select class="form-select" name="professional_id">@foreach($professionals as $p)<option value="{{ $p->id }}">{{ $p->name }}</option>@endforeach</select></div><div class="col-6"><input class="form-control" type="datetime-local" name="starts_at" required></div><div class="col-6"><input class="form-control" type="datetime-local" name="ends_at" required></div><div class="col-12"><input class="form-control" name="reason" placeholder="Motivo"></div></div><div class="card-footer bg-transparent"><button class="btn btn-outline-primary">Bloquear período</button></div></form></div></div></div>
<div class="card ea-v8-card mb-4"><div class="card-header border-0"><strong>Grade semanal</strong></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Profissional</th><th>Local</th><th>Dia</th><th>Horário</th><th></th></tr></thead><tbody>@foreach($rules as $r)<tr><td>{{ $r->professional_name }}</td><td>{{ $r->location_name?:'Todas' }}</td><td>{{ ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'][$r->weekday] }}</td><td>{{ substr($r->starts_at,0,5) }}–{{ substr($r->ends_at,0,5) }}</td><td><form method="POST" action="{{ route('v8.availability.delete',$r->id) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>@endforeach</tbody></table></div></div>
<div class="card ea-v8-card"><div class="card-header border-0"><strong>Ausências</strong></div><div class="table-responsive"><table class="table align-middle mb-0"><tbody>@foreach($absences as $r)<tr><td>{{ $r->professional_name }}</td><td>{{ $r->starts_at }}</td><td>{{ $r->ends_at }}</td><td>{{ $r->reason }}</td><td><form method="POST" action="{{ route('v8.absences.delete',$r->id) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>@endforeach</tbody></table></div></div>
@stop
